name: "task-service-1"

rest:
  host: "localhost"
  port: 64530

redis:
  host: "redis"
  port: 6379
  password: "pwd"
  db: 0
  max-retries: 3

node-id: 3

log:
  service-name: "task-service-1"
  level: 1
  time-format: "2006-01-02T15:04:05Z07:00"
  timestamp-enabled: true
