name: "task-service-local"

rest:
  host: "localhost"
  port: 64530

redis:
  host: "localhost"
  port: 6379
  db: 0
  max-retries: 3

node-id: 1

log:
  service-name: "task-service-local"
  level: 1
  time-format: "2006-01-02T15:04:05Z07:00"
  timestamp-enabled: true
